"""debug boolean columns

Revision ID: 7d34cb51b2aa
Revises: 8fbd3cdfb886
Create Date: 2025-10-16 16:27:19.265845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '7d34cb51b2aa'
down_revision: Union[str, Sequence[str], None] = '8fbd3cdfb886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp', sa.Column('otp_type', sa.String(), server_default=sa.text("'password_reset'"), nullable=False))
    op.alter_column('otp', 'verified',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_index(op.f('ix_otp_otp_type'), 'otp', ['otp_type'], unique=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_index(op.f('ix_otp_otp_type'), table_name='otp')
    op.alter_column('otp', 'verified',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('otp', 'otp_type')
    # ### end Alembic commands ###
