"""Add profile, country, gender

Revision ID: 8fbd3cdfb886
Revises: 
Create Date: 2025-10-13 16:33:25.615842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '8fbd3cdfb886'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_picture', sa.String(), nullable=True))
    op.add_column('users', sa.Column('profile_public_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(), nullable=True))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'num_verify',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_users_num_verify'), table_name='users')
    op.drop_index(op.f('idx_users_phone_number'), table_name='users')
    op.drop_constraint(op.f('users_phone_number_unique'), 'users', type_='unique')
    op.create_index(op.f('ix_users_country'), 'users', ['country'], unique=False)
    op.create_index(op.f('ix_users_gender'), 'users', ['gender'], unique=False)
    op.create_index(op.f('ix_users_num_verify'), 'users', ['num_verify'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_index(op.f('ix_users_profile_picture'), 'users', ['profile_picture'], unique=False)
    op.create_index(op.f('ix_users_profile_public_id'), 'users', ['profile_public_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_profile_public_id'), table_name='users')
    op.drop_index(op.f('ix_users_profile_picture'), table_name='users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_num_verify'), table_name='users')
    op.drop_index(op.f('ix_users_gender'), table_name='users')
    op.drop_index(op.f('ix_users_country'), table_name='users')
    op.create_unique_constraint(op.f('users_phone_number_unique'), 'users', ['phone_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_phone_number'), 'users', ['phone_number'], unique=False)
    op.create_index(op.f('idx_users_num_verify'), 'users', ['num_verify'], unique=False)
    op.alter_column('users', 'num_verify',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('users', 'gender')
    op.drop_column('users', 'country')
    op.drop_column('users', 'profile_public_id')
    op.drop_column('users', 'profile_picture')
    # ### end Alembic commands ###
